import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const roboto = localFont({
  src: [
    { path: "./fonts/Roboto-Regular.woff2", weight: "400" },
    { path: "./fonts/Roboto-Bold.woff2", weight: "700" },
  ],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: process.env.REACT_APP_NAME,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

